import sys
import os
import json
import time
import urllib.request
import re
import requests
import yt_dlp
from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout, 
    QLineEdit, QPushButton, QLabel, QFileDialog, QProgressBar, QTextEdit,
    QListWidget, QListWidgetItem, QAbstractItemView, QMessageBox, QGroupBox, 
    QScrollArea, QCheckBox
)
from PyQt6.QtCore import Qt, QThread, pyqtSignal, QSize, QSettings
from PyQt6.QtGui import QPalette, QColor, QFont, QPixmap

# --- Helper Functions ---
def convert_json_to_netscape(json_path, output_path):
    """Convert JSON cookies to Netscape 7 format"""
    with open(json_path, 'r', encoding='utf-8') as f:
        cookies = json.load(f)
    
    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by Video Scraper to fix JSON error\n")
        for c in cookies:
            domain = c.get('domain', '')
            include_sub = "TRUE" if domain.startswith('.') else "FALSE"
            path = c.get('path', '/')
            secure = "TRUE" if c.get('secure') else "FALSE"
            try:
                expiry = int(float(c.get('expirationDate', time.time() + 31536000)))
            except:
                expiry = int(time.time() + 31536000)
            name = str(c.get('name', ''))
            value = str(c.get('value', ''))
            f.write(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

def prepare_cookie(cookie_src, log_signal=None):
    """Pre-process cookie paths"""
    if not cookie_src: return None
    
    final_cookie_path = None
    if os.path.exists(cookie_src):
        if cookie_src.lower().endswith('.json'):
            try:
                final_cookie_path = os.path.abspath("cookies_converted.txt")
                convert_json_to_netscape(cookie_src, final_cookie_path)
                if log_signal: log_signal.emit(f"[*] Converted {os.path.basename(cookie_src)} to Netscape format")
            except Exception as e:
                if log_signal: log_signal.emit(f"[!] Cookie conversion failed: {str(e)}")
                return cookie_src # Fallback to original
        else:
            final_cookie_path = os.path.abspath(cookie_src)
    return final_cookie_path

# --- Threads ---
class InfoThread(QThread):
    """Video info parsing thread"""
    info_signal = pyqtSignal(dict, bytes) # metadata, thumbnail_bytes
    error_signal = pyqtSignal(str)
    log_signal = pyqtSignal(str)

    def __init__(self, url, cookie_file, proxy=None):
        super().__init__()
        self.url = url
        self.cookie_file = cookie_file
        self.proxy = proxy

    def run(self):
        cookie_path = prepare_cookie(self.cookie_file, self.log_signal)
        
        # Bilibili parsing logic
        if "bilibili.com" in self.url or "b23.tv" in self.url:
            bv_match = re.search(r"(BV[a-zA-Z0-9]+)", self.url)
            if bv_match:
                bvid = bv_match.group(1)
                api_url = f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}"
                headers = {"User-Agent": "Mozilla/5.0", "Referer": "https://www.bilibili.com/"}
                try:
                    res = requests.get(api_url, headers=headers, timeout=10).json()
                    if res.get('code') == 0:
                        data = res['data']
                        entries = []
                        # Handle UGC Seasons
                        if data.get('ugc_season'):
                            for section in data['ugc_season'].get('sections', []):
                                for ep in section.get('episodes', []):
                                    entries.append({'title': ep['title'], 'url': f"https://www.bilibili.com/video/{ep['bvid']}"})
                        # Handle Multi-P
                        elif len(data.get('pages', [])) > 1:
                            for p in data['pages']:
                                entries.append({'title': p['part'], 'url': f"https://www.bilibili.com/video/{bvid}?p={p['page']}"})
                        
                        if entries:
                            info = {
                                'title': data['title'],
                                'thumbnail': data['pic'],
                                'entries': entries,
                                'is_collection': True
                            }
                            self._emit_with_thumb(info)
                            return
                except Exception as e:
                    self.log_signal.emit(f"[*] Bilibili API skip: {e}")

        # YouTube/General logic
        ydl_opts = {
            'extract_flat': True,
            'cookiefile': cookie_path,
            'proxy': self.proxy,
            'nocheckcertificate': True,
            'quiet': True,
        }

        try:
            self.log_signal.emit(f"[*] Analyzing via engine: {self.url}")
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(self.url, download=False)
                
                if 'entries' in info:
                    processed_entries = []
                    for entry in info['entries']:
                        if not entry: continue
                        v_id = entry.get('id') or entry.get('url', '')
                        v_url = v_id if v_id.startswith('http') else f"https://www.youtube.com/watch?v={v_id}"
                        processed_entries.append({'title': entry.get('title', 'Unknown'), 'url': v_url})
                    info['entries'] = processed_entries

            self._emit_with_thumb(info)
        except Exception as e:
            self.error_signal.emit(str(e))

    def _emit_with_thumb(self, info):
        thumb_url = info.get('thumbnail')
        thumb_data = b""
        if thumb_url:
            try:
                req = urllib.request.Request(thumb_url, headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req, timeout=5) as response:
                    thumb_data = response.read()
            except: pass
        self.info_signal.emit(info, thumb_data)

class DownloadThread(QThread):
    """Background download thread"""
    progress_signal = pyqtSignal(dict)
    finished_signal = pyqtSignal(str)
    error_signal = pyqtSignal(str)
    log_signal = pyqtSignal(str)

    def __init__(self, urls, save_path, cookie_file, proxy=None):
        super().__init__()
        self.urls = urls 
        self.save_path = save_path
        self.cookie_file = cookie_file
        self.proxy = proxy

    def run(self):
        cookie_path = prepare_cookie(self.cookie_file, self.log_signal)
        
        ydl_opts = {
            'format': 'bestvideo+bestaudio/best',
            'outtmpl': os.path.join(self.save_path, '%(title)s.%(ext)s'),
            'merge_output_format': 'mp4',
            'progress_hooks': [self._hook],
            'cookiefile': cookie_path,
            'proxy': self.proxy,
            'nocheckcertificate': True,
            'no_warnings': False,
        }

        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                self.log_signal.emit(f"[*] Starting download for {len(self.urls)} tasks...")
                ydl.download(self.urls)
            self.finished_signal.emit("All tasks completed!")
        except Exception as e:
            self.error_signal.emit(str(e))

    def _hook(self, d):
        if d['status'] == 'downloading':
            self.progress_signal.emit(d)
        elif d['status'] == 'finished':
            self.log_signal.emit(f"[Done] File: {os.path.basename(d.get('filename', 'Unknown'))}")

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("HD Video Scraper")
        self.setMinimumSize(QSize(600, 450))
        self.settings = QSettings("SoftZ", "VideoDownloader")
        self.init_ui()
        self.apply_theme()
        self.load_saved_settings()

    def init_ui(self):
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        layout = QVBoxLayout(central_widget)
        layout.setSpacing(10)
        layout.setContentsMargins(15, 15, 15, 15)

        title_label = QLabel("Video Scraper v1.0.0")
        title_label.setFont(QFont("Arial", 14, QFont.Weight.Bold))
        layout.addWidget(title_label)

        input_group = QGroupBox("Task Settings")
        input_layout = QVBoxLayout(input_group)

        # URL Input
        url_layout = QHBoxLayout()
        self.url_input = QLineEdit()
        self.url_input.setPlaceholderText("Paste video link (Supports playlist/collection)")
        self.analyze_btn = QPushButton("Analyze")
        self.analyze_btn.clicked.connect(self.analyze_url)
        url_layout.addWidget(QLabel("URL:"))
        url_layout.addWidget(self.url_input)
        url_layout.addWidget(self.analyze_btn)
        input_layout.addLayout(url_layout)

        # Cookie Input
        cookie_layout = QHBoxLayout()
        self.cookie_input = QLineEdit()
        self.cookie_input.setPlaceholderText("Recommend using Netscape format cookies.txt")
        self.cookie_btn = QPushButton("Browse")
        self.cookie_btn.clicked.connect(self.browse_cookie)
        cookie_layout.addWidget(QLabel("Cookie:"))
        cookie_layout.addWidget(self.cookie_input)
        cookie_layout.addWidget(self.cookie_btn)
        input_layout.addLayout(cookie_layout)

        # Save path
        path_layout = QHBoxLayout()
        self.path_input = QLineEdit(os.path.join(os.getcwd(), "downloads"))
        self.path_btn = QPushButton("Change")
        self.path_btn.clicked.connect(self.browse_path)
        path_layout.addWidget(QLabel("Save To:"))
        path_layout.addWidget(self.path_input)
        path_layout.addWidget(self.path_btn)
        input_layout.addLayout(path_layout)

        # Proxy
        proxy_layout = QHBoxLayout()
        self.proxy_check = QCheckBox("Enable Proxy:")
        self.proxy_input = QLineEdit()
        self.proxy_input.setPlaceholderText("e.g. http://127.0.0.1:1080 or socks5://127.0.0.1:1080")
        proxy_layout.addWidget(self.proxy_check)
        proxy_layout.addWidget(self.proxy_input)
        input_layout.addLayout(proxy_layout)

        self.proxy_check.stateChanged.connect(lambda: self.settings.setValue("proxy_enabled", self.proxy_check.isChecked()))
        self.proxy_input.textChanged.connect(lambda: self.settings.setValue("proxy_address", self.proxy_input.text()))
        
        layout.addWidget(input_group)

        # Preview
        self.preview_group = QGroupBox("Video Preview")
        self.preview_group.setVisible(False)
        preview_layout = QHBoxLayout(self.preview_group)
        
        self.thumb_label = QLabel()
        self.thumb_label.setFixedSize(240, 135)
        self.thumb_label.setScaledContents(True)
        self.thumb_label.setStyleSheet("border: 1px solid gray; background: black;")
        preview_layout.addWidget(self.thumb_label)

        info_list_layout = QVBoxLayout()
        self.title_label = QLabel("Title: -")
        self.title_label.setWordWrap(True)
        self.title_label.setFont(QFont("Arial", 10, QFont.Weight.Bold))
        info_list_layout.addWidget(self.title_label)
        
        self.list_controls = QWidget()
        self.list_controls.setVisible(False)
        list_btn_layout = QHBoxLayout(self.list_controls)
        list_btn_layout.setContentsMargins(0, 0, 0, 0)
        
        self.btn_select_all = QPushButton("Select All")
        self.btn_select_none = QPushButton("Deselect All")
        self.btn_select_all.clicked.connect(self.select_all_items)
        self.btn_select_none.clicked.connect(self.select_none_items)
        
        list_btn_layout.addWidget(self.btn_select_all)
        list_btn_layout.addWidget(self.btn_select_none)
        list_btn_layout.addStretch()
        info_list_layout.addWidget(self.list_controls)

        self.playlist_widget = QListWidget()
        self.playlist_widget.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.playlist_widget.setVisible(False) 
        self.playlist_widget.keyPressEvent = self.playlist_key_press
        self.playlist_widget.itemClicked.connect(self.sync_checkbox_state)
        info_list_layout.addWidget(self.playlist_widget)
        
        preview_layout.addLayout(info_list_layout)
        layout.addWidget(self.preview_group, 1)

        # Control and Status
        self.progress_bar = QProgressBar()
        self.progress_bar.setFixedHeight(20)
        layout.addWidget(self.progress_bar)

        self.download_btn = QPushButton("Download Selected")
        self.download_btn.setFixedHeight(35)
        self.download_btn.setFont(QFont("Arial", 10, QFont.Weight.Bold))
        self.download_btn.setEnabled(False)
        self.download_btn.clicked.connect(self.start_download)
        layout.addWidget(self.download_btn)

        self.log_output = QTextEdit()
        self.log_output.setPlaceholderText("Logs...")
        self.log_output.setMaximumHeight(100)
        self.log_output.setReadOnly(True)
        layout.addWidget(self.log_output)

    def apply_theme(self):
        palette = QApplication.palette()
        is_dark = palette.window().color().lightness() < 128
        
        if is_dark:
            bg_color = "#1e1e1e"
            text_color = "#ffffff"
            input_bg = "#2d2d2d"
            accent_color = "#3498db"
        else:
            bg_color = "#f5f5f5"
            text_color = "#2c3e50"
            input_bg = "#ffffff"
            accent_color = "#2980b9"

        self.setStyleSheet(f"""
            QMainWindow {{ background-color: {bg_color}; }}
            QLabel {{ color: {text_color}; }}
            QLineEdit {{ 
                background-color: {input_bg}; 
                color: {text_color}; 
                border: 1px solid {accent_color}; 
                border-radius: 4px; 
                padding: 5px; 
            }}
            QPushButton {{ 
                background-color: {accent_color}; 
                color: white; 
                border-radius: 4px; 
                padding: 5px 15px; 
            }}
            QPushButton:hover {{ background-color: #2980b9; }}
            QProgressBar {{ 
                border: 1px solid grey; 
                border-radius: 5px; 
                text-align: center; 
                color: {text_color};
            }}
            QProgressBar::chunk {{ background-color: {accent_color}; }}
            QTextEdit {{ 
                background-color: {input_bg}; 
                color: {text_color}; 
                border: 1px solid #ccc;
            }}
        """)

    def browse_cookie(self):
        file, _ = QFileDialog.getOpenFileName(self, "Select Cookie File", "", "Cookies (*.json *.txt)")
        if file: 
            self.cookie_input.setText(file)
            self.settings.setValue("cookie_path", file)

    def load_saved_settings(self):
        saved_cookie = self.settings.value("cookie_path", "")
        if saved_cookie and os.path.exists(saved_cookie):
            self.cookie_input.setText(saved_cookie)
            self.log_output.append(f"[*] Auto-loaded cookie: {os.path.basename(saved_cookie)}")
        
        proxy_enabled = self.settings.value("proxy_enabled", "false") == "true"
        proxy_address = self.settings.value("proxy_address", "")
        self.proxy_check.setChecked(proxy_enabled)
        self.proxy_input.setText(proxy_address)

    def browse_path(self):
        directory = QFileDialog.getExistingDirectory(self, "Select Download Directory")
        if directory: self.path_input.setText(directory)

    def analyze_url(self):
        url = self.url_input.text().strip()
        if not url:
            self.log_output.append("[!] Please enter a video URL first")
            return
        
        proxy = self.proxy_input.text().strip() if self.proxy_check.isChecked() else None
        
        self.analyze_btn.setEnabled(False)
        self.log_output.append(f"[*] Analyzing URL: {url}...")
        
        self.info_thread = InfoThread(url, self.cookie_input.text(), proxy)
        self.info_thread.info_signal.connect(self.on_info_loaded)
        self.info_thread.log_signal.connect(lambda m: self.log_output.append(m))
        self.info_thread.error_signal.connect(self.on_error)
        self.info_thread.finished.connect(lambda: self.analyze_btn.setEnabled(True))
        self.info_thread.start()

    def on_info_loaded(self, info, thumb_data):
        self.preview_group.setVisible(True)
        self.playlist_widget.clear()
        
        title = info.get('title', 'Unknown Title')
        self.title_label.setText(f"Title: {title}")
        
        if thumb_data:
            pixmap = QPixmap()
            pixmap.loadFromData(thumb_data)
            self.thumb_label.setPixmap(pixmap)
        
        if 'entries' in info and len(info['entries']) > 0:
            self.playlist_widget.setVisible(True)
            self.list_controls.setVisible(True)
            self.log_output.append(f"[*] Detected list/collection with {len(info['entries'])} videos")
            
            for i, entry in enumerate(info['entries'], 1):
                item_title = entry.get('title', 'Unknown')
                item_url = entry.get('url') or entry.get('webpage_url')
                display_text = f"[{i:02d}] {item_title}"
                
                item = QListWidgetItem(display_text)
                item.setData(Qt.ItemDataRole.UserRole, item_url)
                item.setFlags(item.flags() | Qt.ItemFlag.ItemIsUserCheckable | Qt.ItemFlag.ItemIsEnabled | Qt.ItemFlag.ItemIsSelectable)
                item.setCheckState(Qt.CheckState.Checked) 
                self.playlist_widget.addItem(item)
            self.current_targets = [] 
        else:
            self.playlist_widget.setVisible(False)
            self.current_targets = [info.get('webpage_url', self.url_input.text())]
            self.log_output.append("[*] Single video analysis complete")

        self.download_btn.setEnabled(True)
        self.download_btn.setText("Download Selected" if self.playlist_widget.isVisible() else "Start Download")

    def start_download(self):
        targets = []
        if self.playlist_widget.isVisible():
            for i in range(self.playlist_widget.count()):
                item = self.playlist_widget.item(i)
                if item.checkState() == Qt.CheckState.Checked:
                    targets.append(item.data(Qt.ItemDataRole.UserRole))
        else:
            targets = self.current_targets

        if not targets:
            QMessageBox.warning(self, "Warning", "Please select at least one video to download")
            return

        self.download_btn.setEnabled(False)
        self.progress_bar.setValue(0)
        save_path = self.path_input.text()
        if not os.path.exists(save_path): os.makedirs(save_path)

        proxy = self.proxy_input.text().strip() if self.proxy_check.isChecked() else None

        self.thread = DownloadThread(targets, save_path, self.cookie_input.text(), proxy)
        self.thread.progress_signal.connect(self.update_progress)
        self.thread.log_signal.connect(lambda m: self.log_output.append(m))
        self.thread.finished_signal.connect(self.on_finished)
        self.thread.error_signal.connect(self.on_error)
        self.thread.start()

    def update_progress(self, d):
        p_str = d.get('_percent_str', '0%').replace('%', '')
        try:
            val = int(float(p_str))
            self.progress_bar.setValue(val)
        except: pass
        
        speed = d.get('_speed_str', 'N/A')
        eta = d.get('_eta_str', 'N/A')
        self.statusBar().showMessage(f"Speed: {speed} | ETA: {eta}")

    def on_finished(self, msg):
        self.log_output.append(f"<b>[Success] {msg}</b>")
        self.download_btn.setEnabled(True)
        self.statusBar().showMessage("Ready")

    def select_all_items(self):
        for i in range(self.playlist_widget.count()):
            self.playlist_widget.item(i).setCheckState(Qt.CheckState.Checked)

    def select_none_items(self):
        for i in range(self.playlist_widget.count()):
            self.playlist_widget.item(i).setCheckState(Qt.CheckState.Unchecked)

    def playlist_key_press(self, event):
        if event.key() == Qt.Key.Key_Space:
            selected_items = self.playlist_widget.selectedItems()
            if not selected_items: return
            
            target_state = Qt.CheckState.Unchecked if selected_items[0].checkState() == Qt.CheckState.Checked else Qt.CheckState.Checked
            self.playlist_widget.blockSignals(True)
            for item in selected_items:
                item.setCheckState(target_state)
            self.playlist_widget.blockSignals(False)
        else:
            QListWidget.keyPressEvent(self.playlist_widget, event)

    def sync_checkbox_state(self, clicked_item):
        selected_items = self.playlist_widget.selectedItems()
        if clicked_item in selected_items:
            new_state = clicked_item.checkState()
            self.playlist_widget.blockSignals(True)
            for item in selected_items:
                item.setCheckState(new_state)
            self.playlist_widget.blockSignals(False)

    def on_error(self, err):
        self.log_output.append(f"<font color='red'>[Error] {err}</font>")
        self.download_btn.setEnabled(True)
        self.analyze_btn.setEnabled(True)
        
        if "Netscape formatted" in err or "cookies" in err.lower():
            self.show_cookie_help()

    def show_cookie_help(self):
        msg = QMessageBox(self)
        msg.setWindowTitle("Cookie Format Guide")
        msg.setIcon(QMessageBox.Icon.Warning)
        msg.setText("Detected cookie file issues. Recommendations:")
        msg.setInformativeText(
            "1. Install <b>Cookie-Editor</b> extension in your browser<br>"
            "2. Open the video site and log in<br>"
            "3. Click extension -> Export -> <b>Netscape HTTP Cookie File</b><br>"
            "4. Save content as cookies.txt and reload in this app"
        )
        msg.exec()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())